name: 'MY-TEST-WF'

on:
  workflow_dispatch:
  push:
    # branches: ["main", "test-*"]
    branches: ["main"]


jobs:
  my-job:
      runs-on: ubuntu-latest
      steps:
        - name: test-step
          run: echo "from test"
    
